[features]
seeds = false

[programs.localnet]
signet = "FeHnvX9LPVHtATNN2XssgiVVLYhPf3wLBoAzfYrgkEbp"

[programs.devnet]
signet = "FeHnvX9LPVHtATNN2XssgiVVLYhPf3wLBoAzfYrgkEbp"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"